### ISSUE TITLE
Failed to fetch the auth bundle: Server returned status code 400

### ISSUE THREAD

**Issue by quangchien99** [daily-demos/rtvi-client-android-demo#4] opened 2024-08-28 11:49 UTC
How can I run the demo, i have config the Daily API Key -> but when run the demo I get the response:

`VoiceClientManager      ai.rtvi.client.basicdemo             E  Future resolved with error: Failed to fetch the auth bundle: Server returned status code 400`

**Comment by quangchien99** [comment] 2024-08-29 02:57
I have update the API KEY and it run.
However, it not speak anything and I got error logs from **CallClient              ai.rtvi.client.basicdemo**

<img width="1523" alt="image" src="https://github.com/user-attachments/assets/d39dd164-28e8-4aff-8816-719ce8b76af2">

**Comment by marcus-daily** [comment] 2024-08-30 12:51
Hi @quangchien99, thanks for the report. Which version/commit of the demo are you using? The URL and API key should be set as follows:

* URL: `https://api.daily.co/v1/bots/start`
* API key: This should be the key here: https://bots.daily.co/dashboard/secrets

**Comment by marcus-daily** [comment] 2024-08-30 12:59
In earlier versions of the app it was necessary for the user to start speaking first before the bot, however this is changed in the latest version. Also the transcription errors above are a known issue which I'll fix soon, however these shouldn't cause a problem with the bots.

**Comment by quangchien99** [comment] 2024-09-05 03:40
Thank you @marcus-daily, is this demo available for starting conversation with bot yet?

After I run this demo the UI is displayed well, but nothing happened? 
In Logcat, I got:
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/ba483df3-44c7-4f8e-8849-d472756565f4">

The demo did not  record my talk, and not speak the bot response as well.

**Comment by quangchien99** [comment] 2024-09-05 03:41
I'm in main branch with commit [Update package name to co.daily.bots.demo](https://github.com/daily-demos/rtvi-client-android-demo/commit/d9a6701d50a0a3cd4ce4a92bdbb9537aa6874c21)

**Comment by marcus-daily** [comment] 2024-09-05 12:38
Thanks @quangchien99! That commit is correct and the bots should start speaking first.

If you let me know the room URL, I could take a look at the server logs to see if there are any issues. There should be a log line that looks like the following, I just need the `room_url` field please:

```
DailyTransport: connect({"room_url":"https://pc-e914d07d216540f4a68f5285363a9732.daily.co/dailybot525df02636924311ae4f1ffe8fe4e82a", ...
```

Do you see any change in the microphone indicator when you speak? Also, what kind of Android device and OS version are you using?

**Comment by goodev** [comment] 2024-09-06 02:37
Got the same error:

`ProfileInstaller         D  Installing profile for co.daily.bots.demo
 DailyTransport           I  setState(Authorizing)
  daily.bots.dem           I  Background young concurrent copying GC freed 58829(4010KB) AllocSpace objects, 3(64KB) LOS objects, 42% free, 5431KB/9373KB, paused 107us total 210.284ms
  VoiceClientManager       E  Future resolved with error: Failed to fetch the auth bundle: Server returned status code 400`

there is no `room_url ` log in the logcat viewer.

**Comment by quangchien99** [comment] 2024-09-06 04:06
Here is my room URL @marcus-daily 
`connect({"room_url":"https://pc-67c85fdeebcee12c0daced13e6c8657c.daily.co/dailybotbaa47472b38e47e1be8a701e12159e5d",...`


It seems everything's working fine, but actually it's not.

Firstly, bot will speak first when start the sample, but I just receive the log and nothing spoken from device speaker.
`Bot transcript: Hello, I'm here to help.`
The UI background turn black

Then after receive log 
`Bot stopped speaking`
-> UI turn grey for user to speak, but when I speak, nothing happen, microphone indicator remains unchanged.

I also tried to test in multiple device but none worked. (Microphone Permission has been granted)
- Google Pixel 4 - Android 13
- Galaxy Z Fold4 - Android 13

https://github.com/user-attachments/assets/b8bae5fd-fa66-4fbc-b813-3c05b312b5b6

Btw, your app is amazing and promising <3

**Comment by quangchien99** [comment] 2024-09-06 04:46
@goodev your API is invalid
Check apiKey in this snippet is valid or not?


```
voiceClientManager.start(
            baseUrl = backendUrl ?: DEFAULT_BACKEND,
            apiKey = apiKey,
            initOptions = initOptions,
            runtimeOptions = runtimeOptions
        )
```

**Comment by goodev** [comment] 2024-09-06 06:05
@quangchien99   the apikey is copyed form here:
![apikey](https://github.com/user-attachments/assets/922064c7-dfe7-42ca-b102-a4909cba7bbe)

**Comment by quangchien99** [comment] 2024-09-06 07:12
@goodev try to replace apiKey right in this code, to check if it work or not

`voiceClientManager.start(
            baseUrl = backendUrl ?: DEFAULT_BACKEND,
            apiKey ="your-api-key-paste-it-here",
            initOptions = initOptions,
            runtimeOptions = runtimeOptions
        )`

**Comment by goodev** [comment] 2024-09-06 07:39
@quangchien99  not working

**Comment by marcus-daily** [comment] 2024-09-06 10:10
@quangchien99 Thank you for the information, I don't see any errors in the server logs.

It might be a problem setting up the WebRTC audio transport. If you could send me the full logcat output for the app please, I could take a look (but make sure the API key and room token isn't visible in the log).

Thank you for persevering with this, hopefully we can find the issue!


@goodev That's unusual, could you try the following `curl` command please and tell me the output?

```
curl --location --request POST 'https://api.daily.co/v1/bots/start' --header 'Content-Type: application/json' --header 'Authorization: Bearer YOUR_API_KEY' --data '{ "bot_profile": "voice_2024_08", "max_duration": 300, "services": { "tts": "cartesia", "llm": "anthropic" }, "config": [] }'
```

The text `YOUR_API_KEY` should be replaced with your key.

**Comment by marcus-daily** [comment] 2024-09-06 12:38
@goodev I've updated the demo to log the HTTP response body, this should indicate why you're getting the 400 error:

https://github.com/daily-demos/rtvi-client-android-demo/commit/73d0afd28feef21ca0dc65e3bac455afd7dec318

Please try again with that commit and let me know the error message. Also, have you modified the demo code in any way?

**Comment by quangchien99** [comment] 2024-09-06 14:13
Oh, I got the problem @marcus-daily , it's due to my company network policy.
It seems to blocking somethings from the demo requests/streaming.

I change to use 4G/public wifi -> it's working perfectly.

It's amazing bro.

Is there anyway that I can modify to use my own:
- STT: I want to use Vietnamese to ask
- TTS Service like Elevenlabs
- LLM Model (Maybe my custom LLM - which expose from Dify)

**Comment by marcus-daily** [comment] 2024-09-06 16:39
@quangchien99 Awesome! Glad to hear it's working.

**STT:** I've added some options for language in the following PR: https://github.com/daily-demos/rtvi-client-android-demo/pull/10 It should be merged soon but you can try it out now.

If you select `Nova 2 General (Multilingual)` at the bottom of the settings menu, a list of languages should appear, including Vietnamese.

**TTS:** Currently only Cartesia is supported, however we're planning to add Elevenlabs next week!

**LLM:** The ones supported at the moment are Anthropic, LLaMa, and also OpenAI and Groq if you add your own API key to the configuration:

https://docs.dailybots.ai/api-reference/client/supportedServices

I'll pass on your suggestion of adding Dify!

**Comment by marcus-daily** [comment] 2024-09-06 16:59
It looks like there's a PR for adding Dify support here: https://github.com/pipecat-ai/pipecat/pull/378

Once it's merged we can expose it via Daily Bots as well!

**Comment by quangchien99** [comment] 2024-09-09 02:43
It's awesome @marcus-daily 
Thank you so much <3

**Comment by quangchien99** [comment] 2024-09-09 03:25
I have test the demo with other languages than English.
I found that due to the `initial_messages` is all in English, this caused the answer is also English too

I suggest to custom the `initial_messages` in VoiceClientManager class like:

```
                ServiceConfig(
                    "llm", listOf(
                        Option("model", runtimeOptions.llmModel.id),
                        Option(
                            "initial_messages", Value.Array(
                                Value.Object(
                                    "role" to Value.Str("system"),
                                    "content" to Value.Str("You are a helpful voice assistant. Keep answers brief, and do not include markdown or other formatting in your responses, as they will be read out using TTS. Please greet the user and offer to assist them. And answer in ${runtimeOptions.sttLanguage.name}")
                                )
                            )
                        ),
                        Option("run_on_config", true),
                    )
                ),
```

But after experimenting, I found that it will use the voice model like "British Lady" to speak other languages (Vietnamese) -> This leads to a really strange conversation :D

Can't wait to see the demo with Elevenlabs And Dify <3

**Comment by goodev** [comment] 2024-09-10 02:23
@marcus-daily {"error":"authorization-header-error","info":"invalid authorization header"}  , do I need create a new apikey?

**Comment by marcus-daily** [comment] 2024-09-12 17:05
@goodev Thanks, I'm able to reproduce that error message if I remove the word "Bearer" from the request header, or otherwise have a malformed header. Could you check the changes you've made to the source code to ensure they're correct?

The `customHeaders` field should be set to: `listOf("Authorization" to "Bearer $key")`, replacing `$key` with your API key.

**Comment by Xiamingmin5** [comment] 2024-09-13 06:30
![777](https://github.com/user-attachments/assets/bae9b76b-eecb-42e4-b03e-3d04aef30797)

I want to use my roomUrl like this ,but can't work.  how to use roomUrl?

**Comment by marcus-daily** [comment] 2024-09-17 09:30
Hi @Xiamingmin5, the URL should be set to an RTVI-compatible backend such as `https://api.daily.co/v1/bots/start`, as this will cause the bot to join the room. If there's something you're trying to achieve by joining a specific room, please let me know and I will help.

**Comment by goodev** [comment] 2024-09-20 07:07
Thanks , after change the customHeaders.  it worked.

**Closed as completed** 2024-10-25 10:19 UTC
